export { default as Hero } from './Hero/Hero'
export { default as About } from './About/About'
export { default as Projects } from './Skill/Skills'
// export { default as Skills } from './Extra/Skills'
export { default as Contact } from './Connect/Connects'
